name: roster_planner
description: Project to improve the workers roster workflow.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  cloud_firestore: ^3.1.9
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.8
  firebase_analytics: ^9.1.2
  firebase_messaging: ^11.2.7

  # UI dependencies
  calendar_timeline: ^1.0.4
  splashscreen:
    git:
      url: https://github.com/DPLYR-dev/SplashScreenFlutterPackage.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
